name: Release Image on Tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Print context
        run: |
          echo "gitea.ref   = ${{ gitea.ref }}"
          echo "gitea.tag   = ${{ gitea.tag }}"
          echo "gitea.sha   = ${{ gitea.sha }}"

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}

      - name: Log in to registry
        run: docker login ${{ vars.REGISTRY_SERVER }} -u ${{ vars.USERNAME }} -p ${{ secrets.PACKAGE_UPLOAD_TOKEN }}

      - name: Extract TAG
        run: |
          REF=${{ gitea.ref }}
          TAG=${REF##refs/tags/v}
          echo "TAG=$TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build -t ${{ vars.REGISTRY_SERVER }}/marinha-si/vulcano-app:$TAG .
          docker tag ${{ vars.REGISTRY_SERVER }}/marinha-si/vulcano-app:$TAG ${{ vars.REGISTRY_SERVER }}/marinha-si/vulcano-app:latest

      - name: Push images
        run: |
          docker push ${{ vars.REGISTRY_SERVER }}/marinha-si/vulcano-app:$TAG
          docker push ${{ vars.REGISTRY_SERVER }}/marinha-si/vulcano-app:latest

      - name: Download Kubectl binaries
        run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

      - name: Install Kubectl
        run: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Extract base64 encoded config
        run: echo "${{ secrets.KUBECONFIG_DSI_PAAS_ENCODED }}" | base64 -d > /tmp/config

      - name: Apply pvc, deployment, service, route
        run: kubectl --kubeconfig=/tmp/config -n ${{ vars.DSI_PAAS_NS }} apply -f k8s/app/

      - name: Update deployment image
        env:
          GITEA_REF: ${{ gitea.ref }}
          DEPLOYMENT_NAME: vulcano-app

        run: |
          echo "TAG=$TAG"
          kubectl --kubeconfig=/tmp/config -n ${{ vars.DSI_PAAS_NS }} set image deployment/vulcano-app vulcano-app=devops-01.marinha.pt/marinha-si/vulcano-app:$TAG
