"""add user model

Revision ID: 356e756aac2c
Revises: a5549928ef5d
Create Date: 2025-10-17 10:45:34.832838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356e756aac2c'
down_revision = 'a5549928ef5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_cliente', sa.String(length=50), nullable=False),
    sa.Column('unidade', sa.String(length=100), nullable=False),
    sa.Column('poc', sa.String(length=100), nullable=True),
    sa.Column('email_poc', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('unidades')
    # ### end Alembic commands ###
