"""Add created_at column to invoices

Revision ID: 6371505e9b60
Revises: 6ababdd636b4
Create Date: 2025-10-24 14:54:48.250572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6371505e9b60'
down_revision = '6ababdd636b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('invoice_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'ND'"))
        batch_op.alter_column('issue_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('taxpayer_number',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('account_number',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('client',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('cvp',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=12),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('invoice_period_year',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=4),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('amount_to_pay',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['invoice_number'])
        batch_op.drop_column('quita_date')

    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.alter_column('email_poc',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('num_cliente'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('display_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('last_login',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('last_login',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               nullable=True)
        batch_op.alter_column('display_name',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               existing_nullable=False)

    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.create_index(batch_op.f('num_cliente'), ['num_cliente', 'unidade'], unique=True)
        batch_op.alter_column('email_poc',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quita_date', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('amount_to_pay',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('invoice_period_year',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=4),
               existing_nullable=True)
        batch_op.alter_column('cvp',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=12),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('client',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
        batch_op.alter_column('account_number',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
        batch_op.alter_column('taxpayer_number',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
        batch_op.alter_column('issue_date',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('invoice_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3),
               nullable=False,
               existing_server_default=sa.text("'ND'"))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
