"""add invoice model

Revision ID: 6ababdd636b4
Revises: 21b0f79abf07
Create Date: 2025-10-17 15:08:57.558809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ababdd636b4'
down_revision = '21b0f79abf07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_type', sa.String(length=50), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.String(length=50), nullable=True),
    sa.Column('taxpayer_number', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('client', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('cvp', sa.String(length=20), nullable=True),
    sa.Column('invoice_period_month', sa.String(length=20), nullable=True),
    sa.Column('invoice_period_year', sa.String(length=10), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('amount_to_pay', sa.Float(), nullable=True),
    sa.Column('sent_validar', sa.Boolean(), nullable=True),
    sa.Column('quitar', sa.Boolean(), nullable=True),
    sa.Column('pdffile', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    # ### end Alembic commands ###
