"""initial migration

Revision ID: a5549928ef5d
Revises: 
Create Date: 2025-10-17 10:33:34.953353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5549928ef5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('num_cliente'))

    op.drop_table('unidades')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('username'))

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('display_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('last_login', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)

    op.create_table('unidades',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('num_cliente', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('unidade', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('poc', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('email_poc', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('num_cliente'), ['num_cliente', 'unidade'], unique=True)

    op.create_table('invoices',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), server_default=sa.text("'ND'"), nullable=False),
    sa.Column('invoice_number', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('issue_date', sa.DATE(), nullable=True),
    sa.Column('taxpayer_number', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('account_number', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('client', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('address', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('cvp', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=12), nullable=True),
    sa.Column('invoice_period_month', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('invoice_period_year', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=4), nullable=True),
    sa.Column('total_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('amount_to_pay', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('sent_validar', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('quitar', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('quita_date', mysql.DATETIME(), nullable=True),
    sa.Column('pdffile', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
