services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

    volumes:
      - ../..:/workspaces:cached
      - ../pdfs:/workspaces/vulcano-app/pdfs
      - ../processed:/workspaces/vulcano-app/processed

    command: sleep infinity
    network_mode: service:db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
    driver: local
