
ALTER TABLE invoices
  DROP COLUMN sent_validar,
  ADD COLUMN irregular TINYINT(1) NOT NULL DEFAULT 0 AFTER amount_to_pay,
  ADD COLUMN pap BIGINT NOT NULL DEFAULT 0 AFTER quita_date,
  ADD COLUMN meo_estado VARCHAR(10) NOT NULL DEFAULT 'NIL' AFTER pap,
  ADD COLUMN obs VARCHAR(70) NOT NULL DEFAULT 'NIL' AFTER meo_estado;
